### ISSUE TITLE
Error when running index.sh

### ISSUE THREAD

**Issue by ekzhu** [TheDataStation/solo#1]
Encountered error when running `index.sh` for custom dataset:

```bash
############:~/open_table_discovery$ ./index.sh custom_tables

Generating triples
Traceback (most recent call last):
  File "index_tables.py", line 342, in <module>
    main()
  File "index_tables.py", line 183, in main
    msg_info = table2graph.main(graph_args)
  File "/home/ekzhu/open_table_discovery/table2txt/table2graph.py", line 79, in main
    num_batch = count_batchs(input_table_file, args.table_import_batch, args.table_chunk_size)
  File "/home/ekzhu/open_table_discovery/table2txt/table2graph.py", line 15, in count_batchs
    for _ in read_tables(data_file, batch_size, chunk_size):
  File "/home/ekzhu/open_table_discovery/table2txt/table2graph.py", line 21, in read_tables
    with open(data_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ekzhu/data/custom_tables/tables/tables.jsonl'
```

It looks like `tables.jsonl` is required but no sure how to produce such file.

**Comment by mingqiwangcn** [comment]
Code is updated and the issue is fixed. Follow the readme for details.
